### ISSUE TITLE
Program stopped at video-id extraction

### ISSUE THREAD

**Issue by chenzixi07** [ujjwal16/edx-lec-dl#1]
I'm using Python 2.7 on Win 7 and ubuntu 14.10. I could successfully login and choose course. But after choosing the course, I got this:

Selected course :
https://www.edx.org/courses/UQx/Write101x/3T2014/info

courseware link:
https://www.edx.org/courses/UQx/Write101x/3T2014/courseware

Starting video-id extraction
Traceback (most recent call last):
  File "edx_login.py", line 128, in <module>
    week=material.find_all('div')
AttributeError: 'NoneType' object has no attribute 'find_all'

If I deleted the # at line 126, I got this:
Starting video-id extraction
You are on page None
Traceback (most recent call last):
  File "edx_login.py", line 128, in <module>
    week=material.find_all('div')
AttributeError: 'NoneType' object has no attribute 'find_all'

Seems something goes wrong from line 125, the beautifulsoup step. I'm not familiar with python so that's all I could do.

**Comment by ujjwal16** [comment]
Thanks for pointing out.I will look into this.

**Comment by ujjwal16** [comment]
I am able to run the code on the course you mentioned . Please check if you are running latest version of code

**Comment by ujjwal16** [comment]
![screenshot 2](https://cloud.githubusercontent.com/assets/10174281/5611372/eb53b8f6-94eb-11e4-8f7b-ad2ba4a87068.png)
I inputted write101x as keyterm.
Please check you have updated packages.

**Comment by chenzixi07** [comment]
problem solved
I changed my language of edX to English, and it works
thx
